export const TICKET_CREATE_REQUEST = "TICKET_CREATE_REQUEST";
export const TICKET_CREATE_SUCCESS = "TICKET_CREATE_SUCCESS";
export const TICKET_CREATE_FAIL = "TICKET_CREATE_FAIL";

export const TICKET_USER_REQUEST = "TICKET_USER_REQUEST";
export const TICKET_USER_SUCCESS = "TICKET_USER_SUCCESS";
export const TICKET_USER_FAIL = "TICKET_USER_FAIL";

export const GET_ALL_TICKETS_REQUEST = 'GET_ALL_TICKETS_REQUEST'
export const GET_ALL_TICKETS_SUCCESS = 'GET_ALL_TICKETS_SUCCESS'
export const GET_ALL_TICKETS_FAIL = 'GET_ALL_TICKETS_FAIL'