export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_REGISTER_REQUEST_BY_ADMIN = "USER_REGISTER_REQUEST_BY_ADMIN";
export const USER_REGISTER_SUCCESS_BY_ADMIN = "USER_REGISTER_SUCCESS_BY_ADMIN";
export const USER_REGISTER_FAIL_BY_ADMIN = "USER_REGISTER_FAIL_BY_ADMIN";
export const NULLIFY_USER_BY_ADMIN = 'NULLIFY_USER_BY_ADMIN'